services:
  frontend:
    build:
      dockerfile: dockerFiles/frontend
    ports:
    - 3000:80
    restart: always
  authservice:
    build:
      dockerfile: dockerFiles/authService
    ports:
    - "3001:8080"
    restart: always
